// data.js
const games = [
    {   /* Checked */
        id: 1,
        title: 'A Plague Tale: Innocence',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Adventure'],
        releaseYear: 2019,
        developer: 'Asobo Studio',
        description: 'A dark and emotional action-adventure game set in plague-ridden medieval France.',
        price: 39.99,
        availability: 'sofort verfügbar',
        // eslint-disable-next-line no-undef
        image: require('./src/pics/a-plague-tale-innocence.webp').default
    },
    {   /* Checked */
        id: 2,
        title: 'Age of Empires II: Definitive Edition',
        platforms: ['PC'],
        genre: ['Strategy'],
        releaseYear: 2019,
        developer: 'Forgotten Empires',
        description: 'A classic real-time strategy game remastered with enhanced graphics and new content.',
        price: 19.99,
        availability: 'sofort verfügbar',
        // eslint-disable-next-line no-undef
        image: require('./src/pics/age-of-empires.webp').default
    },
    {   /* Checked */
        id: 3,
        title: 'Alone in the Dark',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Survival Horror'],
        releaseYear: 2024,
        developer: 'Infogrames',
        description: 'One of the pioneering survival horror games that set the standard for the genre.',
        price: 59.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/alone-in-the-dark.webp').default
    },
    {   /* Checked */
        id: 4,
        title: 'Among Us',
        platforms: ['PC', 'Mobile'],
        genre: ['Social Deduction'],
        releaseYear: 2018,
        developer: 'InnerSloth',
        description: 'A multiplayer game where crewmates try to complete tasks while impostors try to eliminate them.',
        price: 4.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/among-us.webp').default
    },
    {   /* Checked */
        id: 5,
        title: 'Assassin\'s Creed Valhalla: Dawn of Ragnarök',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Adventure'],
        releaseYear: 2022,
        developer: 'Ubisoft',
        description: 'Embark on a new journey as a Viking warrior in the latest installment of the Assassin\'s Creed series.',
        price: 59.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/assassin-s-creed-valhalla-die-zeichen-ragnaroeks.webp').default
    },
    {   /* Checked */
        id: 6,
        title: 'Avatar: Frontiers of Pandora',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Adventure'],
        releaseYear: 2023,
        developer: 'Ubisoft',
        description: 'Explore the beautiful yet dangerous world of Pandora in this action-adventure game based on James Cameron\'s Avatar universe.',
        price: 69.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/avatar-frontiers-of-pandora.webp').default
    },
    {   /* Checked */
        id: 7,
        title: 'Call of Duty: Modern Warfare 3',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['First-Person Shooter'],
        releaseYear: 2023,
        developer: 'Infinity Ward',
        description: 'Experience the thrilling conclusion to the Modern Warfare trilogy as you battle through intense missions across the globe.',
        price: 69.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/call-of-duty-modern-warfare-iii.webp').default
    },
    {   /* Checked */
        id: 8,
        title: 'Cyberpunk 2077: Ultimate Edition',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Role-Playing'],
        releaseYear: 2020,
        developer: 'CD Projekt Red',
        description: 'Immerse yourself in the dystopian future of Night City in this highly anticipated open-world RPG.',
        price: 79.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/cyberpunk-2077-ultimate-edition.webp').default
    },
    {   /* Checked */
        id: 9,
        title: 'Dead by Daylight',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Survival Horror'],
        releaseYear: 2016,
        developer: 'Behaviour Interactive',
        description: 'A multiplayer horror game where one player takes on the role of a killer while the others try to escape.',
        price: 24.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/dead-by-daylight.webp').default
    },
    {   /* Checked */
        id: 10,
        title: 'Destiny 2: Die Finale',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['First-Person Shooter', 'MMORPG'],
        releaseYear: 2023,
        developer: 'Bungie',
        description: 'Continue your epic journey as a Guardian in the ultimate battle against the Darkness in this thrilling sequel.',
        price: 49.99,
        availability: 'ausverkauft',
        image: require('./src/pics/destiny-2-die-finale.webp').default
    },
    {   /* Checked */
        id: 11,
        title: 'Dragon\'s Dogma 2',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Role-Playing'],
        releaseYear: 2024,
        developer: 'Capcom',
        description: 'Embark on an epic adventure in a vast open world filled with mythical creatures and ancient mysteries.',
        price: 49.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/dragon-s-dogma-2.webp').default
    },
    {   /* Checked */
        id: 12,
        title: 'Elden Ring',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Role-Playing'],
        releaseYear: 2022,
        developer: 'FromSoftware',
        description: 'Discover the secrets of the shattered world of Elden Ring in this highly anticipated action RPG.',
        price: 59.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/elden-ring.webp').default
    },
    {   /* Checked */
        id: 13,
        title: 'Fallout 4',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Role-Playing'],
        releaseYear: 2015,
        developer: 'Bethesda Game Studios',
        description: 'Explore the post-apocalyptic wasteland of Boston and shape its future in this epic open-world RPG.',
        price: 29.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/fallout-4.webp').default
    },
    {   /* Checked */
        id: 14,
        title: 'Farming Simulator 22',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Simulation'],
        releaseYear: 2021,
        developer: 'GIANTS Software',
        description: 'Build and manage your own farm, grow crops, raise livestock, and expand your agricultural empire.',
        price: 39.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/farming-simulator-22.webp').default
    },
    {   /* Checked */
        id: 15,
        title: 'Final Fantasy XVI',
        platforms: ['PlayStation'],
        genre: ['Role-Playing'],
        releaseYear: 2023,
        developer: 'Square Enix',
        description: 'Enter a new world of fantasy and adventure in the latest installment of the legendary Final Fantasy series.',
        price: 59.99,
        availability: 'ausverkauft',
        image: require('./src/pics/final-fantasy-xvi.webp').default
    },
    {   /* Checked */
        id: 16,
        title: 'Fortnite: Transformers Pack',
        platforms: ['PC', 'PlayStation', 'Xbox', 'Mobile'],
        genre: ['Battle Royale'],
        releaseYear: 2023,
        developer: 'Epic Games',
        description: 'Join the battle as iconic Transformers characters in the ever-evolving world of Fortnite.',
        price: 24.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/fortnite-transformers.webp').default
    },
    {   /* Checked */
        id: 17,
        title: 'Forza Horizon 5',
        platforms: ['Xbox'],
        genre: ['Racing'],
        releaseYear: 2021,
        developer: 'Playground Games',
        description: 'Experience the thrill of open-world racing and explore stunning landscapes in this acclaimed racing game.',
        price: 49.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/forza-horizon.webp').default
    },
    {   /* Checked */
        id: 18,
        title: 'Genshin Impact',
        platforms: ['PC', 'PlayStation', 'Mobile'],
        genre: ['Action', 'Role-Playing'],
        releaseYear: 2020,
        developer: 'miHoYo',
        description: 'Embark on an epic journey across the magical world of Teyvat and uncover its secrets in this open-world RPG.',
        price: 0,
        availability: 'sofort verfügbar',
        image: require('./src/pics/genshin-impact.webp').default
    },
    {   /* Checked */
        id: 19,
        title: 'Ghost of Tsushima',
        platforms: ['PlayStation'],
        genre: ['Action', 'Adventure'],
        releaseYear: 2020,
        developer: 'Sucker Punch Productions',
        description: 'Become a samurai warrior and defend the island of Tsushima from Mongol invaders in this breathtaking open-world adventure.',
        price: 49.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/ghost-of-tsushima.webp').default
    },
    {   /* Checked */
        id: 20,
        title: 'God of War Ragnarök',
        platforms: ['PlayStation'],
        genre: ['Action', 'Adventure'],
        releaseYear: 2022,
        developer: 'Santa Monica Studio',
        description: 'Join Kratos and Atreus on a new adventure in the realms of Norse mythology in the highly anticipated sequel to God of War.',
        price: 59.99,
        availability: 'ausverkauft',
        image: require('./src/pics/god-of-war-ragnaroek.webp').default
    },
    {   /* Checked */
        id: 21,
        title: 'Gran Turismo 7',
        platforms: ['PlayStation'],
        genre: ['Racing', 'Simulation'],
        releaseYear: 2022,
        developer: 'Polyphony Digital',
        description: 'Experience the ultimate racing simulation with stunning visuals and realistic physics in the latest installment of the Gran Turismo series.',
        price: 69.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/gran-turismo-7.webp').default
    },
    {   /* Checked */
        id: 22,
        title: 'Grand Theft Auto V',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Adventure'],
        releaseYear: 2013,
        developer: 'Rockstar Games',
        description: 'Explore the sprawling open world of Los Santos and embark on a life of crime in this critically acclaimed action-adventure game.',
        price: 29.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/grand-theft-auto-v.webp').default
    },
    {   /* Checked */
        id: 23,
        title: 'Hellblade: Senua\'s Sacrifice',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Adventure'],
        releaseYear: 2017,
        developer: 'Ninja Theory',
        description: 'Journey into the depths of Viking hell and experience the haunting story of Senua in this atmospheric action-adventure game.',
        price: 24.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/hellblade.webp').default
    },
    {   /* Checked */
        id: 24,
        title: 'Helldivers 2',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Twin-Stick Shooter', 'Co-op'],
        releaseYear: 2024,
        developer: 'Arrowhead Game Studios',
        description: 'Join an elite squad of soldiers and engage in intense cooperative battles against alien threats in this top-down shooter.',
        price: 39.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/helldivers-2.webp').default
    },
    {   /* Checked */
        id: 25,
        title: 'Horizon Forbidden West',
        platforms: ['PlayStation'],
        genre: ['Action', 'Adventure'],
        releaseYear: 2022,
        developer: 'Guerrilla Games',
        description: 'Embark on a journey to the mysterious Forbidden West and uncover the secrets of a post-apocalyptic world.',
        price: 59.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/horizon-forbidden-west.webp').default
    },
    {   /* Checked */
        id: 26,
        title: 'League of Legends',
        platforms: ['PC'],
        genre: ['MOBA'],
        releaseYear: 2009,
        developer: 'Riot Games',
        description: 'Join millions of players in the world\'s most popular multiplayer online battle arena game and compete for glory.',
        price: 0,
        availability: 'sofort verfügbar',
        image: require('./src/pics/league-of-legends.webp').default
    },
    {   /* Checked */
        id: 27,
        title: 'Metal Gear Solid: Master Collection',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Stealth', 'Action'],
        releaseYear: 2023,
        developer: 'Konami',
        description: 'Relive the iconic stealth-action adventures of Solid Snake with remastered editions of the Metal Gear Solid series.',
        price: 59.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/metal-gear-solid.webp').default
    },
    {   /* Checked */
        id: 28,
        title: 'Minecraft',
        platforms: ['PC', 'PlayStation', 'Xbox', 'Mobile'],
        genre: ['Sandbox', 'Survival'],
        releaseYear: 2011,
        developer: 'Mojang Studios',
        description: 'Explore, build, and survive in a blocky world filled with endless possibilities in this iconic sandbox game.',
        price: 19.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/minecraft.webp').default
    },
    {   /* Checked */
        id: 29,
        title: 'Monster Hunter: World',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Role-Playing'],
        releaseYear: 2018,
        developer: 'Capcom',
        description: 'Embark on epic hunts and face off against giant monsters in this critically acclaimed action RPG.',
        price: 39.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/monster-hunter-world.webp').default
    },
    {   /* Checked */
        id: 30,
        title: 'Princess Peach: Showtime',
        platforms: ['Nintendo Switch'],
        genre: ['Platformer'],
        releaseYear: 2024,
        developer: 'Nintendo',
        description: 'Join Princess Peach on an exciting adventure to reclaim the Mushroom Kingdom in this charming platformer.',
        price: 49.99,
        availability: 'ausverkauft',
        image: require('./src/pics/princess-peach-showtime.webp').default
    },
    {   /* Checked */
        id: 31,
        title: 'Ranch Simulator',
        platforms: ['PC'],
        genre: ['Simulation'],
        releaseYear: 2021,
        developer: 'Excalibur Games',
        description: 'Build, manage, and expand your own ranch in this realistic farming simulation game.',
        price: 29.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/ranch-simulator.webp').default
    },
    {   /* Checked */
        id: 32,
        title: 'Resident Evil 3',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Survival Horror'],
        releaseYear: 2020,
        developer: 'Capcom',
        description: 'Face terrifying enemies and uncover the truth behind the outbreak in Raccoon City in this thrilling survival horror game.',
        price: 39.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/resident-evil-3.webp').default
    },
    {   /* Checked */
        id: 33,
        title: 'Resident Evil 4',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Survival Horror'],
        releaseYear: 2005,
        developer: 'Capcom',
        description: 'Experience the acclaimed survival horror classic that redefined the genre with its gripping story and intense gameplay.',
        price: 19.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/resident-evil-4.webp').default
    },
    {   /* Checked */
        id: 34,
        title: 'Silent Hill 2 Remake',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Survival Horror'],
        releaseYear: 2023,
        developer: 'Konami',
        description: 'Return to the eerie town of Silent Hill in this modern remake of the survival horror masterpiece.',
        price: 49.99,
        availability: 'vorbestellbar',
        image: require('./src/pics/silent-hill-2.webp').default
    },
    {   /* Checked */
        id: 35,
        title: 'South Park: Snow Day',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['RPG'],
        releaseYear: 2024,
        developer: 'Ubisoft',
        description: 'Join the foul-mouthed kids of South Park on a wacky adventure filled with humor and satire.',
        price: 29.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/south-park-snow-day.webp').default
    },
    {   /* Checked */
        id: 36,
        title: 'Star Wars Battlefront',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Shooter'],
        releaseYear: 2015,
        developer: 'EA DICE',
        description: 'Experience epic battles in the Star Wars universe and fight for the fate of the galaxy in this multiplayer shooter.',
        price: 19.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/star-wars-battlefront.webp').default
    },
    {   /* Checked */
        id: 37,
        title: 'Street Fighter 6',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Fighting'],
        releaseYear: 2023,
        developer: 'Capcom',
        description: 'Prepare for intense battles and iconic matchups in the latest installment of the legendary fighting game series.',
        price: 59.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/street-fighter-6.webp').default
    },
    {   /* Checked */
        id: 38,
        title: 'Suicide Squad',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Adventure'],
        releaseYear: 2024,
        developer: 'Rocksteady Studios',
        description: 'Join the Suicide Squad on a dangerous mission to save the world from a threat unlike any other.',
        price: 49.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/suicide-squad.webp').default
    },
    {   /* Checked */
        id: 39,
        title: 'Super Mario Party (Switch Version)',
        platforms: ['Nintendo Switch'],
        genre: ['Party'],
        releaseYear: 2021,
        developer: 'Nintendo',
        description: 'Gather your friends and family for a fun-filled party experience with classic Mario characters and minigames.',
        price: 49.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/super-mario-party.webp').default
    },
    {   /* Checked */
        id: 40,
        title: 'Tekken 7',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Fighting'],
        releaseYear: 2017,
        developer: 'Bandai Namco Entertainment',
        description: 'Enter the King of Iron Fist Tournament and battle against a diverse cast of fighters in this acclaimed fighting game.',
        price: 29.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/tekken-7.webp').default
    },
    {   /* Checked */
        id: 41,
        title: 'Tekken 8',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Fighting'],
        releaseYear: 2024,
        developer: 'Bandai Namco Entertainment',
        description: 'Prepare for the next evolution of the King of Iron Fist Tournament in the highly anticipated sequel to Tekken 7.',
        price: 59.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/tekken-8.webp').default
    },
    {   /* Checked */
        id: 42,
        title: 'The Elder Scrolls V: Skyrim',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Role-Playing'],
        releaseYear: 2011,
        developer: 'Bethesda Game Studios',
        description: 'Embark on an epic adventure in the frozen land of Skyrim and fulfill your destiny as the Dragonborn.',
        price: 29.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/the-elder-scrolls-v-skyrim.webp').default
    },
    {   /* Checked */
        id: 43,
        title: 'The Legend of Zelda: Breath of the Wild',
        platforms: ['Nintendo Switch'],
        genre: ['Action', 'Adventure'],
        releaseYear: 2017,
        developer: 'Nintendo',
        description: 'Explore the vast kingdom of Hyrule and uncover its secrets in this critically acclaimed open-world adventure.',
        price: 59.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/the-legend-of-zelda-breath-of-the-wild.webp').default
    },
    {   /* Checked */
        id: 44,
        title: 'The Witcher 3: Wild Hunt',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Role-Playing'],
        releaseYear: 2015,
        developer: 'CD Projekt Red',
        description: 'Embark on a quest of epic proportions and become a monster slayer in this critically acclaimed open-world RPG.',
        price: 29.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/the-witcher-3.webp').default
    },
    {   /* Checked */
        id: 45,
        title: 'Tomb Raider I, II, III: Remastered',
        platforms: ['PC', 'PlayStation', 'Xbox'],
        genre: ['Action', 'Adventure'],
        releaseYear: 2024,
        developer: 'Crystal Dynamics',
        description: 'Relive the classic adventures of Lara Croft in stunning remastered editions of the original Tomb Raider trilogy.',
        price: 49.99,
        availability: 'sofort verfügbar',
        image: require('./src/pics/tomb-raider-i-iii-remastered.webp').default
    },
    {   /* Checked */
        id: 46,
        title: 'Uncharted',
        platforms: ['PlayStation'],
        genre: ['Action', 'Adventure'],
        releaseYear: 2022,
        developer: 'Naughty Dog',
        description: 'Join treasure hunter Nathan Drake on a globe-trotting adventure to uncover ancient mysteries and lost treasures.',
        price: 19.99,
        availability: 'sofort verfügbar',
        // eslint-disable-next-line no-undef
        image: require('./src/pics/uncharted.webp').default
    },
];

export default games;